# Generated by Django 4.2.9 on 2024-01-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mc_donalds', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
